### ISSUE TITLE
remotes::install_github defaults to master branch

### ISSUE THREAD

**Issue by alicebyers5** [Public-Health-Scotland/phstemplates#29]
Hi Alan,

Just tried to install this and got an error using the code copied from the Readme. Turns out in older versions of remotes, the default branch is "master", so I had to run the following to install - `remotes::install_github("Public-Health-Scotland/phstemplates", ref = "main")`.

I think newer versions of remotes and devtools look for both master and main, but just wondered if it's worth updating the code in the Readme for users with older versions?

Thanks,
Alice

**Comment by alan-y** [comment]
thanks @alicebyers5 - I didn't realise this, I think it's worth adding the `ref = "main"` argument in anyway for completeness.
