### ISSUE TITLE
Auto-fill the script header text 

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phstemplates#34]
I think some of the bits of text in the script header could be auto-filled. I'm referring to `script_template.R` but would need some changes elsewhere too.

- [ ] For the '(delete if using version control)' lines, we can check if the git has been ticked then do something like ` ifelse(using_git, NA, "# Original date (delete if using version control)")`.
- [ ] Written / Run on - We could check `version`
- [ ] Version of R ... - As above check `version`

There's a chance that these would be incorrect, e.g. someone ticks git but then never uses it, or opens the project on the desktop then changes to server / different version etc. but I think there would be a benefit in terms of time typing out those few lines but mostly by increasing the accuracy and consistency of those notes at the top of scripts.

**Comment by alan-y** [comment]
Thanks for the suggestions - yeah this all sounds good. Should be able to add this in for the next version

**Comment by alan-y** [comment]
These suggestions have now been implemented
