### ISSUE TITLE
Error when trying to start with renv

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phstemplates#36]
I'm pretty sure this used to work for me but now when creating a project with renv ticked I get an error:
```
Initialized empty Git repository in /home/jamesm32/test-renv-git/.git/
Error in getOption("error") : option error has NULL value
```
This is accompanied by an 'R code execution error' pop up. I've tried a couple of combos of basic options (all on the server) and it seems to only be the renv tickbox that causes it.

RStudio fails to open a session with the new project too. It looks like most things work though: the project is created, git is initialised and the renv cache settings have been written to the .Rprofile. renv doesn't seem to have been initialised though, and the general infrastructure hasn't been created by it.

I tried running all the lines of:
```R
    if (renv) {
        if (!"renv" %in% utils::installed.packages()[, 1]) {
            warning("renv is not installed. Now attempting to install...",
                    immediate. = TRUE)
            utils::install.packages("renv")
        }

        if (Sys.info()[["sysname"]] != "Windows" && file.access("/conf/linkage/output/renv_cache", mode = 2) == 0) {
            renv_rprofile <- "Sys.setenv(RENV_PATHS_ROOT = \"/conf/linkage/output/renv_cache\")"
        } else if (Sys.info()[["sysname"]] == "Windows" && file.access("//stats/cl-out/renv_cache/Windows_test", mode = 2) == 0) {
            renv_rprofile <- "Sys.setenv(RENV_PATHS_ROOT = \"//stats/cl-out/renv_cache/Windows_test\")"
        } else {
            renv_rprofile <- ""
        }
        writeLines(renv_rprofile, con = file.path(path, ".Rprofile"))

        renv::init(project = file.path(getwd(), path))
    }
```

My only thought is; should `renv::init(project = file.path(getwd(), path))` be `renv::init(project = file.path(path))`? Otherwise I'm stumped!

**Comment by alan-y** [comment]
I need to review this code - I think the whole renv cache thing is of the table now so will try to look into it and update for the next version.

**Comment by alan-y** [comment]
@Moohan - would you be ok with me removing all the global cache stuff? I think we can't go down this route on server anymore due to file permissions problems.
When I looked into this a little, it looks like the renv package now (v0.14 is what I'm using) creates a `.Rprofile` in the directory so I'm not sure I can create my own `.Rprofile` now as it does that and will overwrite it. We'd need to find another way to do automatic setting of a global cache if we want this functionality in future...

**Comment by Moohan** [comment]
Yeah no problem with me. I'm totally out of the loop on what happened to the renv global cache idea. I think it probably makes sense to have the settings set by default in the server set-up rather than per project here though.

**Comment by alan-y** [comment]
PHS has RStudio Package Manager included in the bundle so despite all the previous work we've done to suggest we may not need it, we can use it if we have it anyway 🙂 
I can't remember what was exactly said but it was along the lines of the global cache directory not being possible since permissions seem to keep getting reset or something - there were ways around this like running scripts to continually loop through users and set permissions but don't think this was particularly straightforward, especially as the user list is constantly changing...

**Comment by alan-y** [comment]
@Moohan - I've looked in this error a bit. It looks like it comes up with the newer version of renv and will be fixed when we get a newer version of Rstudio installed:
https://community.rstudio.com/t/error-option-error-has-null-value/37605/3
https://community.rstudio.com/t/error-option-error-has-null-value-on-version-3-6-1/39856

If you really want to create a new project with renv option in phstemplates, you can still do so by using the code (changing the arguments to what you want):
```
phstemplates::phsproject("test_renv", author = "alan", renv = TRUE)
```
or by creating a new project from the menu first without renv ticked and then running `renv::init()` afterwards

A final option is to revert to an older version of renv

I also noticed that with the latest version of renv, you need to provide 'consent' to modify some files the first time you use the package. I've updated the function to hopefully do that automatically for users.

Unfortunately that's all we can do for now though...

**Comment by bevthewitch** [comment]
Hi, not sure if this is related but I've just tried to create a brand new PHS Shiny app with the use renv tickbox checked and get this error:

![image](https://github.com/Public-Health-Scotland/phstemplates/assets/52245506/4d6f18bf-321d-49d4-a4e6-ba1a21e1e3d2)

Given that we are now on Workbench does this mean the issue persists?

**Comment by alan-y** [comment]
@bevthewitch - I've had a test of this. Looks like Posit just doesn't like that it takes ages to create the shiny project when renv is ticked as it has to install loads of packages that the shiny template depends on.
It all worked very smoothly when renv was not ticked so I'd recommend not using the renv option for the shiny template. You can always run renv after creating the shiny template.

**Comment by bevthewitch** [comment]
OK thanks Alan, I was just interested to see what the template looked like anyway.

Bev Dodds | Principal Information Analyst
Pronouns: she/her/hers

Public Health Scotland
Email: ***@***.******@***.***>
[Public Health Scotland logo]
Web<http://www.publichealthscotland.scot/> | Twitter<https://twitter.com/P_H_S_Official> | Instagram<https://www.instagram.com/publichealthscotland/> | Facebook<https://m.facebook.com/people/Public-Health-Scotland/100083220736554/>

***@***.***

**Comment by alan-y** [comment]
I'm going to close this issue as I don't think the original issue is there anymore.
