### ISSUE TITLE
Function to add `.gitignore` to existing project

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phstemplates#45]
The standard `.gitignore` in phstemplates has some nice defaults for ignoring data files etc. it would be good to easily be able to add it to an existing project, with something like `phstemplates::add_gitignore(overwrite = TRUE)` which would add the .gitginore, if there's an already an existing one, it could append (default) or overwrite.

**Comment by alan-y** [comment]
This sounds good - any volunteers to work on it @Moohan @RosalynLP ? 😃
Or I can find some time hopefully in the next little while to do it. I have another couple of minor changes to make to the package as well.

**Comment by Moohan** [comment]
Sorry, pretty swamped for at least the next few weeks / month... That's why I've just been commenting on our various packages and not actually providing any work 😛

**Comment by alan-y** [comment]
No worries haha, I don't think it'll take too long so I can try to find a spare hour or so in the next week or 2

**Comment by RosalynLP** [comment]
@alan-y happy to look into this

**Comment by alan-y** [comment]
That would be great thanks @RosalynLP  - I'll be happy to review if you can draft up a function for it.
