### ISSUE TITLE
Create PHS R Shiny App won't overwrite existing directory

### ISSUE THREAD

**Issue by bevthewitch** [Public-Health-Scotland/phstemplates#50]
I was trying out the PHS Shiny template but didn't realise I hadn't got phstemplates package loaded, so created a new Shiny project directory called test Shiny app. I closed the session, restarred and installed phstermplates, then tried to create a new Shiny app following the instructions - I checked the overwrite existing directory (if Apresent) but I got an error message basically saying I couldn't reuse the same project folder name.

![image](https://github.com/Public-Health-Scotland/phstemplates/assets/52245506/14d4ad1c-01da-4e63-8a11-d355b7a56ed8)
![image](https://github.com/Public-Health-Scotland/phstemplates/assets/52245506/eaab5f02-65cd-4220-acba-30cf649c2a8c)

**Comment by RosalynLP** [comment]
@bevthewitch Hm this is an interesting error - thanks for letting us know! It could be something to do with the change to Posit again? I know this functionality at least used to work on the old server. I'll have a look into it when I get some time and get back to you.

**Comment by alan-y** [comment]
Hi @RosalynLP, I picked this up as an issue through testing previously. Older versions of RStudio (POSIT) seem to allow the overwriting option but newer ones do not. So this is why it would've worked on the older server but not the current Workbench. I don't have a solution for it unfortunately...

**Comment by alan-y** [comment]
@RosalynLP I don't think it's possible to fix this issue as when you use the RStudio project menu option, it checks if the folder is present (and doesn't allow you to create a project) before running through the code in your function. I think all we can do is remove the `overwrite` option from the menu but leave it there for interactive use from the R console - what do you think?

**Comment by RosalynLP** [comment]
@alan-y I think in this case we'll just have to remove the overwrite option - it's probably not of that much use in any case
