### ISSUE TITLE
R CMD fails because of suggested dep `gdtools` on R < 4.0

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phstemplates#53]
`{gdtools}` is in the DESCRIPTION as a Suggest, so this is unlikely to affect any users but I also couldn't see anywhere that gdtools was being used in the package, so maybe it could just be removed as a dependency?

https://github.com/Public-Health-Scotland/phstemplates/actions/runs/5420848676/jobs/9855521943?pr=52#step:5:154

**Comment by RosalynLP** [comment]
Seemed to be added in this commit https://github.com/Public-Health-Scotland/phstemplates/commit/d20589d166b91e2a12d7a8f6489731d64df251b3 for reference

**Comment by alan-y** [comment]
I think it was to do with Travis CI or Github Actions. Likely to do with running on different versions of R but I'm not sure if this is still needed...

**Comment by Moohan** [comment]
On other repos I do latest + versions we have available on PWB (4.1.2, 4.02 and 3.6.1).

I'd love to have some more structure and policy around how we're doing packages but I it's not there yet!
