### ISSUE TITLE
Add space to enter the PWB settings in `script_template.R`

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phstemplates#54]
This was raised at the R technical meeting a while ago, essentially one suggestion for ensuring people use the minimal environment they can, was to add a note at the top of scripts saying what PWB environment is required. e.g.

```
# PWB Options #
# CPUs - 1
# Memory - 4096 MB
```

The above text could just be added as a default, and/or there could be prompts, or it's probably even possible to look up the settings programmatically (although this option might lead to overly large values being entered without the initial user realising and then future users taking them as gospel!)

**Comment by alan-y** [comment]
I'm happy to adopt this if the group has made a decision on this? I don't think these should be picked up programatically but probably based on the user thinking it through

**Comment by r6lm** [comment]
Thanks for pointing this to me @Moohan. I did not know about the existence of this repo.

@alan-y , there is no agreement indeed. I can ask for it when this is made clear. I was suggesting the following RStudio code snippet as `header`. Maybe there are a couple of ideas that can be useful for the `script_template.R`
```
snippet header  
  #' `r basename(rstudioapi::getSourceEditorContext()$path)` 
  #' Some Team  
  #' Code written `r format(Sys.Date(), "%B %Y")` 
  #' `r R.Version()$version.string`  
  #' Posit Workbench - ${1:X}GB ${2:N}CPU  
  #' Max-memory: ? GB - Run time: ? s  
  #'  
  #' ${3:Code Overview}  
```

This snippet requires the `rstudioapi` package installed, and with that it can populate the name of the script programmatically. Furthermore, the <`{1}`, `{2}`, `{3}`, `…`> syntax comes from the [snippet syntax](https://rstudio.github.io/rstudio-extensions/rstudio_snippets.html), so I believe that cannot be replicated in the `script_template.R`.

Finally, the ideal for me would be to register the maximum memory and the runtime programmatically. However, I am still unsure of how this could be done. I wrote documentation in how to measure this [using the RStudio Profiling Tool](https://public-health-scotland.github.io/knowledge-base/docs/Posit%20Infrastructure?doc=How%20to%20Use%20the%20R%20Studio%20Profiling%20Tool.md).

**Comment by alan-y** [comment]
@r6lm - can snippets be included in an R package and installed for a user. I'm happy to discuss ideas for how to implement this. I find myself having to update the metadata on existing scripts so I'm looking into better ways to do that.
