### ISSUE TITLE
Adding markdown templates for experimental statistics and management information publications

### ISSUE THREAD

**Issue by elliejwbatesphs** [Public-Health-Scotland/phstemplates#56]
### **Enhancement to add templates for two additional styles of publication commonly produced by PHS**

Currently the Spark has word templates for management information and experimental statistics publications,.

This package does not appear to have these, though existing official statistics and national statistics templates could be adapted.

Would it be possible to add them please?

**Comment by alan-y** [comment]
Thanks @elliejwbatesphs - I will need to have a look at these templates and see if they will be straightforward to add in. Not sure when I will have time for it yet but also happy if anybody else wants to develop these?

**Comment by elliejwbatesphs** [comment]
Thanks @alan-y - I have a piece of work where I am going to try and adapt the management information template so I can use it to produce a PHS internal report (may become external later). Very happy to share the markdown and base template produced to do this once I'm done - but will likely need some help with the process of creating a skeleton etc. so it can be added to the template options in the R studio menu.

**Comment by elliejwbatesphs** [comment]
@alan-y I have a working PHS management information report markdown template and related docx files. I have created a branch in a local clone of the phstemplates repo with a temporary folder with these templates in. However I don't seem to have permissions to push a new branch to the repo

Error
<remote: Permission to Public-Health-Scotland/phstemplates.git denied to elliejwbatesphs.
fatal: unable to access 'https://github.com/Public-Health-Scotland/phstemplates.git/': The requested URL returned error: 403>

Can you or someone give me permissions to create a branch?

**Comment by alan-y** [comment]
sounds great, access granted now. Thanks

**Comment by elliejwbatesphs** [comment]
Thanks - have created the branch - have got the management info report into the inst folder and appropriate sub-folder and tested and seems to be working ok.
Plan to create the management information summary template as well which should hopefully be straightforward before raising a pull request

**Comment by elliejwbatesphs** [comment]
@alan-y I've now got templates for Management Information publications in my branch
https://github.com/Public-Health-Scotland/phstemplates/tree/elliebates
see folders in inst/rmarkdown/templates
phs-mnginfo-report
phs-mnginfo-summary

I've tested them and everything is working, I managed to get the changes to pass checks and install into R studio.

I've checked the outputs against the PHS templates on the spark.
Everything looks correct **except** I cannot get the Title at the top of the Management Information Summary output document (produced on knitting the markdown) to automatically pick up the Publication Title style as it should. 
I think this is something to do with the underlying word document template but I'm not sure what (I've basically copied the markdown directly from the markdown used for the national stats and official stats summary templates  which do pick up the Publication Title correctly; I've changed very little and I haven't changed anything related to styles in my revised version.

 I am not sure how to force the Title at the top of the output to use the Publication Title style. I don't think this is a fatal issue as you can format the Title to Publication Title style in the word document produced by knit afterwards - but obviously it would be better if this worked in the output automatically.

If someone could take a look at the management information summary template I've produced, and see if they can work out how to fix this, that would be great.

**Comment by alan-y** [comment]
Hi @elliejwbatesphs, this is great work thanks - I'll try to take a look at it soon. There are lots of little things about RMarkdown output to MS Word that usually take a bit of trial-and-error to get right.

**Comment by alan-y** [comment]
> Everything looks correct except I cannot get the Title at the top of the Management Information Summary output document (produced on knitting the markdown) to automatically pick up the Publication Title style as it should.
@elliejwbatesphs - in the cover page document, you will notice that 'Title' is in it's own text-box. You just have to delete that text-box and re-type 'Title' in it's place. Then everything will work, this is what I done for the other templates.

**Comment by elliejwbatesphs** [comment]
@alan-y I fixed the title issue and added an additional one page template (which also could works if you have two or more pages and need something for e.g. responding in a 3 page work document to an IR). I've put in a pull request for this with you as reviewer - hope that's ok.
