### ISSUE TITLE
Question: why is the .Rproj included in the `.gitignore` file?

### ISSUE THREAD

**Issue by Lextuga007** [Public-Health-Scotland/phstemplates#77]
https://github.com/Public-Health-Scotland/phstemplates/blob/de7891b3625b43c106df012ab4037f2c3da02f5d/inst/text/gitignore.txt#L19

We've had a discussion about this in my organisation (across a few teams but logged here as an [issue](https://github.com/The-Strategy-Unit/data_science/issues/84) and exploring the use of this package we noticed it's in the generated `.gitignore` but not the actual repository (but might have been missed).

**Comment by Moohan** [comment]
@alan-y might have a different view but I think the reasons we ignore it are:

1. It's rare that the settings in the .Rproj are ever changed (which would be the only useful thing to track).
2. When you clone a repo from GitHub using RStudio (GUI) it will automatically generate an Rproj with the name of the repo e.g. `repo-name.Rproj` - If there is an Rproj file in the repo already with a different name, you will now confusingly have 2 .Rproj files (with RStudio using the new (default settings) `repo-name.Rproj` one).

Hopefully, that is clear!

I do take the points mentioned [in the forum](https://community.rstudio.com/t/should-rproj-files-be-added-to-gitignore/1269/5) but I think for the PHS use case, we have consistent settings already from our shared infrastructure and if a project needs to use the Rproj for settings a user can deviate from the .gitignore.

**Comment by alan-y** [comment]
I agree with what @Moohan has said.
But if you feel that tracking .Rproj settings is useful for your own purposes, then it's, of course, fine to remove it from gitignore.

A point I'd add is that the gitignore we generate for phstemplates is to be considered as defaults for users but they can edit these for individual projects if they wish.

**Comment by Moohan** [comment]
[heart]         James McMahon reacted to your message:
________________________________
