### ISSUE TITLE
Introduction might not always be necessary

### ISSUE THREAD

**Issue by RosalynLP** [Public-Health-Scotland/phstemplates#87]
The `compile_report` function expects there to be an "Introduction" section in the Rmd and doesn't work if there isn't one. However, it might not always be appropriate to have a section explicitly named "Introduction" in the report and we'd still like the function to work.

**Comment by alan-y** [comment]
Hi @RosalynLP, is there another keyword we should be searching for instead of 'Introduction' or is there sometimes no first section heading? We could create an argument for the first section heading.
