### ISSUE TITLE
remove white space on left and right from banner

### ISSUE THREAD

**Issue by johannajokio** [Public-Health-Scotland/phstemplates#99]
currently, the coloured banner has gaps on left and right end of page; but if you include links at the bottom, they don't align with the left 'edge' of the banner. I'm sure this can be fixed in the html, I just haven't managed yet

**Comment by alan-y** [comment]
Can add a white version of the PHS logo and users can choose, e.g. https://scotland.shinyapps.io/phs-medicines-in-pregnancy/
